server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  shutdown_timeout: 5s

database:
  host: localhost
  port: 5432
  user: prateekkumar
  password: ""
  dbname: chat_app
  sslmode: disable
jwt:
  secret_key: "super-secret-key-that-is-at-least-32-characters"
  access_expiry: 15m
  refresh_expiry: 24h

auth:
  password_min_length: 8
